name: jira-description-action
on:
  pull_request:
    types: [opened, edited]
jobs:
  add-jira-description:
    runs-on: ubuntu-latest
    steps:
      - uses: cakeinpanic/jira-description-action@v0.2.0
        name: jira-description-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: '${{ secrets.JIRA_EMAIL }}:${{ secrets.API_TOKEN }}'
          jira-base-url: https://project-sunbird.atlassian.net
          use: both
